<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run()
    {
        // Hapus semua data lama (termasuk dummy)
        DB::table('products')->truncate();

        // Data produk dari SQL dump (20 produk real)
        $products = [
            [
                'category_id' => 3,
                'name' => 'Subwoofer Aktif Kolong 12 Inch Venom VX 12.2 A',
                'price' => 1400000,
                'stock' => 20,
                'description' => 'Venom VX 12.2 A adalah subwoofer aktif jenis underseat (kolong) berukuran 12 inci yang dirancang untuk menghasilkan dentuman bass yang lebih dalam dan bertenaga...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/WWUexWwfVZNVCsbXgxoodmryif7xMfh6pOZhBazc.png',
                'weight' => 5000,
                'dimensions' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Central Door Lock System RRD',
                'price' => 250000,
                'stock' => 20,
                'description' => 'Sistem Central Door Lock dari RRD merupakan modul aktuator elektrik (pistol pengunci) universal...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/0I5y4OUEVNaiKmeat8YlFYEH4JUwBTPAwNHE9eR0.png',
                'weight' => 600,
                'dimensions' => '23x11x8',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Parking Assistant System IPF-P02 (Two Sensors)',
                'price' => 250000,
                'stock' => 20,
                'description' => 'IPF-P02 Parking Assistant System adalah sensor parkir mundur universal dua titik...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/MnlIPnmSxmi2a2eQ746N6HunYZVbikyOHa6kyQ55.png',
                'weight' => 500,
                'dimensions' => '17x12x6.5',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Tweeter Mobil Dome Lambo Style (Set)',
                'price' => 150000,
                'stock' => 20,
                'description' => 'Tweeter komponen mikro jenis dome universal yang dirancang untuk meningkatkan detail frekuensi tinggi...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/RPa3kfcVYZJNH07fJSQGIbJ0kFKexpz5uJIrEm6U.png',
                'weight' => 300,
                'dimensions' => '16x11x5',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Lampu Halogen Mobil Bellford Super Bright H4',
                'price' => 40000,
                'stock' => 100,
                'description' => 'Lampu bohlam halogen utama (headlight) dari Bellford tipe H4...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/X8OFt0gKuRnoJdkQKEsn23r7howTp9kK3Ho0ggZ7.png',
                'weight' => 150,
                'dimensions' => '10x5x5',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Talang Air Mobil (Slim Series)',
                'price' => 400000,
                'stock' => 100,
                'description' => 'Talang air mobil (door visor) model slim yang berfungsi untuk mencegah air hujan masuk ke dalam kabin...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/muJ38A5Qgaqjr5nDfHHK4MoQxTfwYLR74r5pB3sh.png',
                'weight' => 1999,
                'dimensions' => '105x15x5',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Head Unit MP5 Audiobank 7 Inch (AB-TV6912)',
                'price' => 650000,
                'stock' => 30,
                'description' => 'Audiobank AB-TV6912 adalah Head Unit tipe MP5 deckless (tanpa pemutar CD/DVD) berukuran 7 inci...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/YfT7BnhglglpoGJ69VA02kZm8HIHDCPzDkwfJCWt.jpg',
                'weight' => 1499,
                'dimensions' => '21x15x15',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Foglamp Biled MAZEL 70 Watt',
                'price' => 1200000,
                'stock' => 10,
                'description' => 'Lampu kabut (foglamp) tipe Bi-LED dari MAZEL yang dirancang dengan sistem proyektor...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/483KRGnYzhFSLSkMGhh4zTj4kSmKJmT9wvj59dpM.jpg',
                'weight' => 1000,
                'dimensions' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Cable Spiral / Clock Spring Toyota 84306-BZ160',
                'price' => 425000,
                'stock' => 19,
                'description' => 'Suku cadang clock spring atau cable spiral original untuk kendaraan Toyota/Lexus...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/aYkbm81lgL0y2dBx77SeeEGPl2WUvebhRnA6GBni.jpg',
                'weight' => 500,
                'dimensions' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Kipas Angin Mobil Three-Headed Vehicle Fan',
                'price' => 185000,
                'stock' => 28,
                'description' => 'Kipas angin mobil dengan tiga kepala yang dapat diputar 360 derajat...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/xQFBGdbsc4klABL8Tm2zsZU3MgsNHz2HvNdsRBf2.jpg',
                'weight' => 648,
                'dimensions' => '30x15x12',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Sirine Klakson SONICX X168 Wireless (4 Sound Style)',
                'price' => 250000,
                'stock' => 20,
                'description' => 'Klaxon sirine elektrik model corong yang dirancang dengan 4 variasi suara sirine berbeda...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/0B8uq7r9HIbZa4kaCPorVikpxh3ysR5RzTpAOtCu.jpg',
                'weight' => 1499,
                'dimensions' => '20x18x18',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Speaker Venom Elemento Veto 6 (Split Component)',
                'price' => 525000,
                'stock' => 100,
                'description' => 'Speaker komponen (split) Venom seri Elemento Veto 6 dirancang untuk meningkatkan kualitas audio mobil...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/wUUKTJdaArrF2WmET9fCDdlNMW8Udq76rMwgjoi5.jpg',
                'weight' => 3000,
                'dimensions' => '45x25x15',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 4,
                'name' => 'Power Amplifier Venom Elemento V-460.4',
                'price' => 1800000,
                'stock' => 20,
                'description' => 'Power amplifier 4-channel dari Venom seri Elemento V-400.4 yang dirancang untuk mendongkrak performa audio mobil Anda...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/hJBmTorYHEIODCXXaQwCaUzcPEGswO35bAuuvWlh.jpg',
                'weight' => 3000,
                'dimensions' => '35x26x8',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Lampu Tembak LED Proyektor 3 Mata Bulat (Set)',
                'price' => 700000,
                'stock' => 20,
                'description' => 'Lampu tembak sorot (auxiliary worklight) universal dengan desain 3 mata lensa proyektor bulat sejajar...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/5FG2Z4p38XPzCJaZalKo9uj8iirBcgxFGTKYk9hD.jpg',
                'weight' => 1000,
                'dimensions' => '22x13x9',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Android Audiobank 10.1 Inch (AB-TV6911 Alaska 6)',
                'price' => 1200000,
                'stock' => 20,
                'description' => 'Audiobank AB-TV6911 dari seri Alaska 6 adalah Head Unit Android multimedia berukuran 10.1 inci...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/co1E9oEcK8cmPTyO1xSYuatb89sCq4BqDCB2Xe5h.jpg',
                'weight' => 1999,
                'dimensions' => '30x20x12',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Klakson Keong Fortress Snail Horn (118dB)',
                'price' => 225000,
                'stock' => 50,
                'description' => 'Fortress Snail Horn adalah klakson variasi mobil tipe keong (snail) berkinerja tinggi...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/IYy9N62OsKCpZZFGqpXQr0DikRPkUKyjivv7PIQN.jpg',
                'weight' => 700,
                'dimensions' => '16x11x10',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Klakson Keong Denso Power Tone (Waterproof)',
                'price' => 300000,
                'stock' => 30,
                'description' => 'Denso Power Tone adalah klakson variasi mobil tipe keong (snail horn) premium yang dirancang dengan keunggulan tahan air...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/31c6ISa5Uatu75ogRMPoxBpH5zV664oE9Wv99xcH.jpg',
                'weight' => 700,
                'dimensions' => '17x12x10',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Alarm Mobil Silicon Premium Series (SP-17)',
                'price' => 400000,
                'stock' => 40,
                'description' => 'Sistem keamanan mobil terpadu dari Silicon Premium Series tipe SP-17...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/3D3vdohvZjZi2YTUMyHwfFyukffY2uJ6ylEzhBoU.jpg',
                'weight' => 800,
                'dimensions' => '18x12x9.5',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Non-Slip Sport Pedal Pad ISOKA TRD Sportivo (ISK-299)',
                'price' => 185000,
                'stock' => 100,
                'description' => 'Set cover pedal manual (sport pedal pad) dari ISOKA dengan aksen desain TRD Sportivo berwarna merah-hitam...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/jcGLBV9sDdCLBChypaCKvV8GXWMgAa2h1dKChitB.jpg',
                'weight' => 400,
                'dimensions' => '22x17x3',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'name' => 'Alarm Mobil VRD Car Security System (Highest Quality)',
                'price' => 300000,
                'stock' => 20,
                'description' => 'Sistem keamanan mobil terpadu dari VRD yang berfungsi sebagai perangkat anti-maling...',
                'image_url' => 'http://127.0.0.1:8000/storage/products/JQq55bcAESIK9Mi9Z4hRgloZFSffCQuaPYz4h9pc.jpg',
                'weight' => 800,
                'dimensions' => '18x12x9.5',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert semua produk
        foreach ($products as $product) {
            DB::table('products')->insert($product);
        }
    }
}