name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        script: |
          [ -d "app" ] || git clone https://github.com/${{ github.repository }}.git app
          cd app
          git pull origin main
          echo "${{ secrets.ENV_FILE }}" > .env
          docker-compose up -d --build
          docker-compose exec -T laravel php artisan migrate --force
